name: Veight Zhou
description: 机巧少年不会黑魔法
meta_description:

markdown: kramdown
krandown: 
    input: GFM
#highlighter: pygments
logo: false
gems: [jekyll-paginate]
paginate: 15
paginate_path: "page:num"
baseurl: /
# domain_name: 'http://veightz.net'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
# url:            'veightz.net'
author:         'Veight Zhou'
